// lib/phonePrefix.js
// Mapping pays (nom FR stocké en base) → indicatif téléphonique

export const COUNTRY_PHONE_PREFIX = {
  "Afghanistan":              "+93",
  "Afrique du Sud":           "+27",
  "Albanie":                  "+355",
  "Algérie":                  "+213",
  "Allemagne":                "+49",
  "Angola":                   "+244",
  "Arabie Saoudite":          "+966",
  "Émirats Arabes Unis":      "+971",
  "Argentine":                "+54",
  "Australie":                "+61",
  "Autriche":                 "+43",
  "Belgique":                 "+32",
  "Bénin":                    "+229",
  "Birmanie":                 "+95",
  "Bolivie":                  "+591",
  "Brésil":                   "+55",
  "Burkina Faso":             "+226",
  "Burundi":                  "+257",
  "Cameroun":                 "+237",
  "Canada":                   "+1",
  "Chili":                    "+56",
  "Chine":                    "+86",
  "Colombie":                 "+57",
  "Congo":                    "+242",
  "Corée du Sud":             "+82",
  "Côte d'Ivoire":            "+225",
  "Cuba":                     "+53",
  "Danemark":                 "+45",
  "Egypte":                   "+20",
  "Espagne":                  "+34",
  "États-Unis":               "+1",
  "Ethiopie":                 "+251",
  "Finlande":                 "+358",
  "France":                   "+33",
  "Gabon":                    "+241",
  "Ghana":                    "+233",
  "Grèce":                    "+30",
  "Guinée":                   "+224",
  "Haïti":                    "+509",
  "Hongrie":                  "+36",
  "Inde":                     "+91",
  "Indonésie":                "+62",
  "Iran":                     "+98",
  "Irlande":                  "+353",
  "Israël":                   "+972",
  "Italie":                   "+39",
  "Jamaïque":                 "+1876",
  "Japon":                    "+81",
  "Kenya":                    "+254",
  "Liban":                    "+961",
  "Luxembourg":               "+352",
  "Madagascar":               "+261",
  "Mali":                     "+223",
  "Maroc":                    "+212",
  "Martinique":               "+596",
  "Maurice":                  "+230",
  "Mauritanie":               "+222",
  "Mexique":                  "+52",
  "Mozambique":               "+258",
  "Namibie":                  "+264",
  "Niger":                    "+227",
  "Nigeria":                  "+234",
  "Norvège":                  "+47",
  "Nouvelle-Zélande":         "+64",
  "Ouganda":                  "+256",
  "Pakistan":                 "+92",
  "Pays-Bas":                 "+31",
  "Pérou":                    "+51",
  "Philippines":              "+63",
  "Pologne":                  "+48",
  "Portugal":                 "+351",
  "RDC":                      "+243",
  "République Dominicaine":   "+1809",
  "Rodrigues":                "+230",
  "Roumanie":                 "+40",
  "Royaume-Uni":              "+44",
  "Rwanda":                   "+250",
  "Sénégal":                  "+221",
  "Sierra Leone":             "+232",
  "Singapour":                "+65",
  "Somalie":                  "+252",
  "Soudan":                   "+249",
  "Suède":                    "+46",
  "Suisse":                   "+41",
  "Tanzanie":                 "+255",
  "Tchad":                    "+235",
  "Togo":                     "+228",
  "Tunisie":                  "+216",
  "Turquie":                  "+90",
  "Ukraine":                  "+380",
  "Uruguay":                  "+598",
  "Venezuela":                "+58",
  "Vietnam":                  "+84",
  "Zimbabwe":                 "+263",
};

/**
 * Retourne le préfixe pour un pays donné (nom FR).
 * Ex: getPrefixForPays("Maurice") → "+230"
 */
export function getPrefixForPays(pays) {
  if (!pays) return "";
  return COUNTRY_PHONE_PREFIX[pays] || "";
}
